config/routes.rb
MapsqueakProto::Application.routes.draw do

  resources :share_requests, :except => [:edit, :destroy]
  resources :squeak_checks, :except => [:destroy]

  get "sessions/new"
  get "users/new"
 
  resources :squeaks
  get "squeaks/new"
  match 'squeaks/map_preview/:id', :to => 'squeaks#map_preview'
  match 'squeaks/image/:id', :to => 'squeaks#squeak_image'
  match 'squeaks/map_image/:id', :to => 'squeaks#map_image'
  match "squeak_search", :to => 'squeaks#search'

  match '/index', :to => 'squeaks#index'
  match '/mobile', :to => 'pages#mobile_app'
  match '/news',    :to => 'pages#news'
  match '/about',    :to => 'pages#about'
  match '/terms',    :to => 'pages#terms'
  match '/contact',    :to => 'pages#contact'
  match '/admin', :to => 'pages#admin'

  root :to => 'squeaks#proper_home'

  resources :users
  get "user_search", :to => "users#search"

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signout/:provider', :to => 'sessions#destroy'
  
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    
  </nav>
<%= yield :scripts %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">	
    <ul>
      <li> <h1>MapSqueak! </h1> </li>	
      <li> </li>
      <li>
	<%= link_to "Home", index_path %>
      </li>
      <li>
	<%= link_to "App", mobile_path %>
      </li>
      <li>
	<%= link_to "News", news_path %>
      </li>
      <li>
	<%= link_to "Terms", terms_path %>
      </li>
      <li>
	<%= link_to "Contact", contact_path %>
      </li>
      <li> <% if signed_in? %>
      <li>
	<%= link_to "Profile", current_user %>
      </li>
      <% end %>
      <li>
	<%= link_to "Logins", signin_path %>
      </li>
      <% if current_user && current_user.admin? %>
      <li>
	<%= link_to "Admin", admin_path %>
      </li>
      <% end %>

      <li> <%= link_to logo, squeaks_new_path %> </li>
    </ul> 
  </nav>
  <nav class="round"> 
    <ul>
      
      
    </ul> 
  </nav>
  <%= yield :head %>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	
  <head>
   <%	if  @squeak and @squeak_map_link %> 
	<meta name="description" content="<%=@squeak.text%>" />
	<meta property="og:title" content="<%=@squeak.text%>" />
	<meta property="og:image" content="<%= @squeak_map_link %>" />
    <meta property="place:location:latitude"  content="<%= @squeak.latitude %>"/> 
    <meta property="place:location:longitude" content="<%= @squeak.longitude %>"/> 

	<% end %> 
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>